# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      build_version:
        enabled: true

builders:
  build_version:
    import: "package:build_version/builder.dart"
    builder_factories: ["buildVersion"]
    build_extensions: {"$lib$": ["version.dart"]}
    build_to: source
    auto_apply: dependents
  build_version_part:
    import: "package:build_version/builder.dart"
    builder_factories: ["buildVersionPart"]
    build_extensions: {"$lib$": [".version.g.dart"]}
    build_to: source
