name: build_pubspec_example
description: This is an example description. Great job! Awesome package.
publish_to: 'none'
authors:
  - Vince Varga <vince.varga@serial.dev>

version: 9.8.7

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.0.0
  build_pubspec:
    path: ../../

# For more info, read:
# https://github.com/flutter/flutter/issues/62240
# https://github.com/flutter/flutter/issues/63556
# Analyzer+Build issues, but they are tracked in flutter.
dependency_overrides:
  analyzer: '0.39.14'
