name: build_pubspec_example
description: This is an example description.
publish_to: 'none'
authors:
  - Vince Varga <vince.varga@dartside.dev>

version: 0.1.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.0.0
  build_pubspec:
    path: ../../
